lokos_shop:
    resource: "@LokosShopBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

lokos_user:
    resource: "@LokosUserBundle/Resources/config/routing.yml"
    prefix:   /