parameters:
  lokos.shop.cart_repository.class: Lokos\ShopBundle\Repositories\CartRepository

services:
  lokos.shop.cart_repository:
    class: %lokos.shop.cart_repository.class%
    arguments:
      - '@doctrine.orm.entity_manager'

  lokos.shop.dist_rewrite:
      class: Lokos\ShopBundle\Assetic\Filter\RewriteFilter
      tags: [{ name: assetic.filter, alias: publish_dist_rewrite }]